language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: process.env.HEROKU_PAPI_KEY
    app: part-time-pups-fe
    on: 
      repo: evanmarkowitz/part-time-pups-fe